version: "3.1"

services:
  database:
    container_name: sbrest_db
    image: influxdb:1.4.2
    environment:
      INFLUXDB_DB: sbrestdb
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: userpass
    ports:
      - "8086:8086"
    networks:
      - back-tier
    volumes:
      - influxdb-volume:/var/lib/influxdb

  appserver:
    build:
       context: .
       dockerfile: Dockerfile
    image: sbrest_app
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  influxdb-volume:
